// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace oneGame
{
    using QFramework;
    using UniRx;

    public class UIAboutPanelData : QFramework.UIPanelData
    {
    }
    
    public partial class UIAboutPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIAboutPanelData ?? new UIAboutPanelData();
            // please add init code here
        }

        protected override void RegisterUIEvent()
        {
            BtnBack.OnClickAsObservable().Subscribe(_ =>
            {
                SendMsg(new AudioSoundMsg("click"));
                CloseSelf();
            });
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
