// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace oneGame
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIAboutPanel
    {
        
        public const string NAME = "UIAboutPanel";
        
        [SerializeField()]
        public Text TxtTitleAbout;
        
        [SerializeField()]
        public Text TxtContentAbout;
        
        [SerializeField()]
        public Button BtnBack;
        
        private UIAboutPanelData mPrivateData = null;
        
        public UIAboutPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIAboutPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            TxtTitleAbout = null;
            TxtContentAbout = null;
            BtnBack = null;
            mData = null;
        }
    }
}
