// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace oneGame
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIGamePausePanel
    {
        
        public const string NAME = "UIGamePausePanel";
        
        [SerializeField()]
        public Image PauseSplash;
        
        [SerializeField()]
        public Animator ButtonBackHome;
        
        private UIGamePausePanelData mPrivateData = null;
        
        public UIGamePausePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIGamePausePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            PauseSplash = null;
            ButtonBackHome = null;
            mData = null;
        }
    }
}
