// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace oneGame
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIStoryPanel
    {
        
        public const string NAME = "UIStoryPanel";
        
        [SerializeField()]
        public Text TxtStoryContent;
        
        [SerializeField()]
        public Button BtnSkip;
        
        private UIStoryPanelData mPrivateData = null;
        
        public UIStoryPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIStoryPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            TxtStoryContent = null;
            BtnSkip = null;
            mData = null;
        }
    }
}
