// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace oneGame
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using DG.Tweening;
    using QFramework;

    public class UIStoryPanelData : QFramework.UIPanelData
    {
    }
    
    public partial class UIStoryPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIStoryPanelData ?? new UIStoryPanelData();
            // please add init code here

            var text = TxtStoryContent.text;
            TxtStoryContent.text = string.Empty;
            TxtStoryContent.DOText(text, 10.0f)
                .OnComplete(() =>
                {
                    OpenGamePanel();
                });
        }

        protected override void RegisterUIEvent()
        {
            BtnSkip.onClick.AddListener(() =>
            {
                TxtStoryContent.DOKill();

                OpenGamePanel();
            });
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }

        private void OpenGamePanel()
        {
            CloseSelf();
            UIMgr.OpenPanel<UIGamePanel>(new UIGamePanelData()
            {
                //DeathCount = 0,
                InitLevelName = "Level1"
            });
        }
    }
}
