// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace oneGame
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UITrainModePanel
    {
        
        public const string NAME = "UITrainModePanel";
        
        [SerializeField()]
        public UILevelItem UILevelItemTemplate;
        
        [SerializeField()]
        public Button BtnBack;
        
        [SerializeField()]
        public RectTransform Content;
        
        private UITrainModePanelData mPrivateData = null;
        
        public UITrainModePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UITrainModePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            UILevelItemTemplate = null;
            BtnBack = null;
            Content = null;
            mData = null;
        }
    }
}
